---

name: swin_t
gops: [9.0, 18.0, 36.0, 72.0]

shapes:
  - [1, 3, 224, 224]
  - [2, 3, 224, 224]
  - [4, 3, 224, 224]
  - [8, 3, 224, 224]

model: $(home)/swin_t.onnx

precision: true

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(model)
    --test_input $(root)/dataset/samples/cat.jpg
    --input_shapes [$(shape_param)]
    --mean 123.68,116.78,103.94
    --scale 0.017,0.017,0.017
    --pixel_format rgb
    --resize_dims 256,256
    --keep_aspect_ratio
    --test_result $(name)_top_outputs.npz
    --mlir $(workdir)/transformed.mlir

BM1684X:
  deploy:
    - model_deploy.py --mlir $(workdir)/transformed.mlir
        --quantize F32
        --chip bm1684x
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.99,0.99
        --model $(workdir)/$(name)_bm1684x_f32.bmodel

  dataset:
    image_path: $(imagenet2012_val_set)
    image_label: $(imagenet2012_caffe_val_ground_truth)
    mean: [123.68, 116.78, 103.94]
    scale: [0.017, 0.017, 0.017]
    size: 224
    trans: True
    bgr2rgb: True

  harness:
    type: efficientnetv2
    args:
      - name: F32
        bmodel: $(root)/output/swin_t-1x3x224x224/swin_t_bm1684x_f32/ \
          compilation.bmodel
