---

name: swin_t
gops: 9.0

time: true

model: $(home)/swin_t.onnx
input_shapes: "[1,3,224,224]"
batch_sizes: [1, 2, 4, 8]

int8_model: $(workdir)/$(name)_bmneto_deploy_int8_unique_top.prototxt
int8_weight: $(workdir)/$(name)_bmneto.int8umodel

BM1684X:
  fp_loops:
    - build_env: [ ]
      fp_outdir_template: "{}b.fp32.compilation"
      prec: FP32

  fp_batch_sizes: [1]
  fp_compile_options:
    python3 -m bmneto
      --model $(model)
      --shapes $(input_shapes)
      --net_name $(name)
      --target $(target)
      --enable_profile true

  time_only_cali:
    python3 -m ufw.cali.cali_model
      --model $(model)
      --input_shapes $(input_shapes)
      --net_name $(name)
      --target $(target)
      --cali_iteration 1
      --test_iterations 1
      --debug_cmd "not_call_bmnetu;not_suspend;use_fake_data_to_test"

  bmnetu_batch_sizes: $(batch_sizes)
  bmnetu_options:
    --model $(int8_model)
    --weight $(int8_weight)
    --target $(target)
    --enable_profile True
