---

name: mobileseg-mlir
gops: [2.58, 5.16, 10.32, 20.64, 41.28]

shapes:
  - [1, 3, 640, 320]
  - [2, 3, 640, 320]
  - [4, 3, 640, 320]
  - [8, 3, 640, 320]
  - [16, 3, 640, 320]

model: $(home)/mobileseg.onnx

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(model)
    --test_input $(root)/dataset/samples/cat.jpg
    --input_shapes [$(shape_param)]
    --mean 127.5,127.5,127.5
    --scale 0.00784,0.00784,0.00784
    --pixel_format bgr
    --test_result $(name)_top_outputs.npz
    --mlir $(workdir)/transformed.mlir

#mlir_calibration:
#    run_calibration.py $(workdir)/transformed.mlir
#    --dataset $(cali_dataset)
#    --input_num 10
#    -o $(home)/cali_table

deploy:
  - model_deploy.py --mlir $(workdir)/transformed.mlir
      --quantize F32
      --chip bm1684x
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.99,0.99
      --model $(workdir)/$(name)_bm1684x_f32.bmodel
  - model_deploy.py --mlir $(workdir)/transformed.mlir
      --quantize INT8
      --calibration_table $(home)/cali_table
      --quant_input
      --quant_output
      --chip bm1684x
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.98,0.85
      --model $(workdir)/$(name)_bm1684x_int8_sym.bmodel
