---

name: Test NNTC
on:
  push:
  pull_request:
    branches: [main]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # UTC time 22:30
    # Saturday
    - cron: '30 22 * * 6'
  workflow_dispatch:
    inputs:
      cases:
        description: 'Cases to run'
        default: '--full'
        required: false
        type: string

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || \
    github.run_id }}"
  cancel-in-progress: true

jobs:
  test_build:
    if: github.repository == 'sophgo/model-zoo'
    name: NNTC Build
    runs-on: build
    timeout-minutes: 10080
    outputs:
      NNTC_MODEL_TAR: ${{ steps.test.outputs.NNTC_MODEL_TAR }}

    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: false
          lfs: false

      - name: LFS Pull
        run: git lfs pull --exclude '' --include '*'

      - name: Set Optional Env
        if: "${{ github.event_name == 'schedule' || \
                 contains( \
                   github.event.pull_request.labels.*.name, \
                   'full_regression' \
                 ) }}"
        run: |
          echo "FULL_TEST=true" >> $GITHUB_ENV

      - name: Test
        run: ".github/workflows/test.sh -m 'build and nntc' ${{ inputs.cases }}"
        id: test

      - name: Cleanup
        if: ${{ cancelled() || failure() }}
        run: .github/workflows/cleanup.sh

  test_runtime:
    if: github.repository == 'sophgo/model-zoo'
    name: ${{ matrix.target }} ${{ matrix.host-arch }} NNTC Runtime
    strategy:
      matrix:
        target: [BM1684, BM1684X]
        host-arch: [X64, ARM64]
    runs-on: [runtime, '${{ matrix.host-arch }}', '${{ matrix.target }}']
    timeout-minutes: 10080
    needs: test_build

    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: false
          lfs: false

      - name: LFS Pull
        run: git lfs pull --exclude '' --include 'dataset/*'

      - name: Set Optional Env
        if: "${{ github.event_name == 'schedule' || \
                 contains( \
                   github.event.pull_request.labels.*.name, \
                   'full_regression' \
                 ) }}"
        run: |
          echo "FULL_TEST=true" >> $GITHUB_ENV

      - name: Test
        run: |
          .github/workflows/test.sh -m 'runtime and nntc' -t \
              ${{ matrix.target }} ${{ inputs.cases }}
        env:
          NNTC_MODEL_TAR: ${{ needs.test_build.outputs.NNTC_MODEL_TAR }}

      - name: Cleanup
        if: ${{ cancelled() || failure() }}
        run: .github/workflows/cleanup.sh
